name: hive_local_storage
description: A cache helper which uses hive and flutter_secure_storage to make ease to store session and encrypted data
version: 0.0.6
homepage: https://github.com/kishor98100/local_storage
repository: https://github.com/kishor98100/local_storage

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter:
